# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-12 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_title', models.CharField(max_length=30)),
                ('image_description', models.TextField(max_length=100)),
                ('image_category', models.CharField(max_length=30)),
                ('image_location', models.CharField(max_length=50)),
                ('cover', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
