# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-14 16:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('photoz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default=datetime.datetime(2019, 12, 14, 16, 6, 7, 482166, tzinfo=utc), max_length=30),
            preserve_default=False,
        ),
    ]
