# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-12 08:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photoz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='cover',
            new_name='image',
        ),
    ]
