# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-16 05:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photoz', '0002_category_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['image_title']},
        ),
    ]
