# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-16 05:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photoz', '0003_auto_20191216_0812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_image',
        ),
    ]
