# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-12 11:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photoz', '0004_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='image_url',
        ),
    ]
