# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-16 05:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photoz', '0004_remove_category_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='image_url',
        ),
    ]
