# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-13 09:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('photoz', '0005_auto_20191212_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.ImageField(default=datetime.datetime(2019, 12, 13, 9, 51, 42, 211414, tzinfo=utc), upload_to='images/'),
            preserve_default=False,
        ),
    ]
