# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-13 12:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('photoz', '0006_category_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='image_url',
            field=models.ImageField(default=datetime.datetime(2019, 12, 13, 12, 24, 28, 802629, tzinfo=utc), upload_to='images/'),
            preserve_default=False,
        ),
    ]
